config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, to: 'bookings#index'

  resources :articles do
    resources :ratings, only: [:new, :create, :show]
  end
  # resources :ratings, only: [:new, :create, :show]
 #test
  # resources :bookings, except: %i[new edit create] do
  #   resources :ratings, only: %i[index show create]
  # end
  #resources :users, only: [:index, :show]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :article
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :init_booking, only: %i[show]
  before_action :init_article, only: [:create, :new]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.article = @article
    @booking.users_id = current_user.id
    if @booking.save! 
      # redirect_to :articles_path(@articles), notice: "Réservation pour votre #{@article}, faite avec succée !"
      redirect_to articles_path(@articles)
    else
      render :new
    end
  end

  def show
    
  end

  def edit
  end

  def update
  end




  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def init_booking
    @booking = Booking.find(params[:id])
  end

  def init_article
    @article = Article.find(params[:article_id])
  end
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@article, @booking] do |f| %>
  <%= f.input :start_date, label: 'Début de la location' %>
  <%= f.input :end_date, label: 'Fin de la location' %>
  <%= f.button :submit %>
<% end %>

<%#= simple_form_for(@booking) do |f| %>
  <%#= f.input :start_date %>
  <%#= f.input :end_date %>
  <%#= f.input :article_id %>
  <%# <%= f.input :created_at %>
  <%# <%= f.input :updated_at %>
  <%# f.input :users_id, value: "#{current_user.id}"%>
  <%#= f.submit class: "btn btn-primary" %>
<%# end %>

app/views/bookings/index.html.erb
    <script>
        setTimeout(window.alert("Vous avez une promotion sur votre prochaine réservation ! - 10%"), "10000");
    </script>
<div class="container mt-5" style="margin-top: 100px!important;"><br>
    <% @bookings.each do |booking| %>
    <%#= if booking != current_user %>
        <h3 class="mt-5"> Date de votre réservation : <%= booking.start_date %></h3>
        <h3>Date de remise en main propre de votre article : <%= booking.end_date %></h3>
        <%# else %>
        <% "Vous n'avez pas encore de réservation 😔" %><br>
        <%= link_to "Faire une réservation", articles_path, class: "btn btn-primary" %>
        <%# end %>
    <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Votre booking</h1>
<div class="container mt-5">
<h2>booking</h2>
<%= render 'form', booking: @booking %>

<hr>
<%#= link_to "Retour", bookings_path %>
<%# <i class="fa-solid fa-arrow-rotate-left"></i> Retour %>

</div>